### <center> EXPERIMENT 2
## <center> NUMERICAL PYTHON (NUMPY)

##### Name: TRANGIA, Klein Isshi G.
##### Section: 2ECE-B
##### Date Submitted: September 3, 2025

In [3]:
import numpy as np

#### __NORMALIZATION PROBLEM__: 

In [5]:
x = np.random.random((5,5))
print (x)

[[0.9943272  0.54327418 0.53581679 0.59699794 0.75927188]
 [0.41185034 0.0347623  0.86802791 0.66257301 0.92451545]
 [0.73218196 0.14936367 0.14731639 0.39119072 0.83348226]
 [0.70998332 0.57385411 0.66984838 0.84306403 0.41798711]
 [0.71799961 0.17256427 0.06445378 0.25941953 0.82706615]]


In [6]:
a = x.mean()

In [7]:
b = x.std()

In [8]:
normal = (x-a)/b
print (normal)

[[ 1.57591005 -0.03709661 -0.06376493  0.15502443  0.73533082]
 [-0.50708025 -1.8555814   1.12425228  0.38952687  1.32625686]
 [ 0.6384548  -1.44575646 -1.45307773 -0.58096093  1.00071389]
 [ 0.55907045  0.07226001  0.41554425  1.03497919 -0.4851346 ]
 [ 0.58773742 -1.36278902 -1.74940199 -1.0521867   0.97776931]]


In [9]:
np.save ('X_normalized.npy', normal)

#### __DIVISIBLE BY 3 PROBLEM__:

In [11]:
k = np.arange(1,101)
i = np.square(k)
g = i.reshape(10,10)

print (g)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [12]:
t = g [g%3==0]
print (t)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]


In [13]:
np.save ('div_by_3.npy', t)